### ISSUE TITLE
Keep the state of the machine in the URL

### ISSUE THREAD

**Issue by rexim** [siggy/beatboxer#3]
I'd be cool if the beats I made were encoded somehow in the URL automatically so I could easily share them with my friends. :)

---

Awesome stuff, btw! Thanks for making it! :+1:

**Comment by J2TEAM** [comment]
:+1:  I have the same idea with you! :grinning:

**Comment by siggy** [comment]
I like this idea! Until I get it implemented here, someone else already did it!
http://www.bambax.com/beatboxer/#||||||x||||||||||||||x||||||||x||||x||||||||x||x||||||||||||||||||||x||120

**Comment by ko-dever** [comment]
I did not know that someone already developed this app.
In other words, we just have to copy-paste bambax project and improve it...

**Comment by siggy** [comment]
Boom! Courtesy of @J2TeaM:
https://github.com/siggy/beatboxer/pull/11

**Comment by rexim** [comment]
@siggy @J2TeaM cool! Thank you very much guys! You're the best!
